## ---- include = FALSE----------------------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>", out.width = "100%",
  fig.width = 7, fig.height = 4, dev = "CairoPNG", dpi = 150, fig.path = "vignettes/",
  message = FALSE, warning = FALSE, error = FALSE
)

## ----setup, include =F---------------------------------------------------------------
library(MeanRarity)


## ----compute rarity------------------------------------------------------------------
# for a totally even distribution, Hill diversity is the same regardless of `l`

even_comm <- rep(2, 6)
rarity(even_comm, 1) # richness
rarity(even_comm, -1) # Hill-Simpson

all.equal(rarity(even_comm, 0), rarity(even_comm, 0.34), rarity(even_comm, 1))

# for uneven communities, Hill diversity depends on `l`

uneven_comm <- c(20, 8, 5, 4, 2, 1)

l_vals <- c(1, 0, -1, 0.34)


data.frame(l = l_vals
           , Hill = sapply(l_vals, function(l){
                    rarity(uneven_comm, l)})
)



## ----effective numbers---------------------------------------------------------------
uneven_12 <- c(531, 186, 101,  63, 41, 28, 19, 13, 9, 5, 3, 1)
even_3 <- c(20, 20, 20)

rarity(uneven_comm, -1) %>% round(2)
rarity(uneven_12, -1) %>% round(2)
rarity(even_3, -1) %>% round(2)



## ----Balance plot setup--------------------------------------------------------------

rich_bal <- rarity_plot(ab = uneven_comm, l = 1, base_size = 12) +
  ggplot2::labs(x = "") +
  ggplot2::scale_color_brewer(type = "qual", palette = "Dark2")

shan_bal <- white_y(rarity_plot(ab = uneven_comm, l = 0, base_size = 12, verbose = F)) + #do not return all the text this time
  ggplot2::scale_color_brewer(type = "qual", palette = "Dark2")

simp_bal <- white_y(rarity_plot(ab = uneven_comm, l = -1, base_size = 12, verbose = F)) +
  ggplot2::labs(x = "") +
  ggplot2::scale_color_brewer(type = "qual", palette = "Dark2")


## ----Balance plot print, fig.width = 3, fig.height = 3-------------------------------
rich_bal
shan_bal
simp_bal



## ----fit species abundance distributions---------------------------------------------
# set target richness and Hill-Simpson diversity levels
rich <- 20
simpson <- 12
even_SAD <- fit_SAD(rich = rich, simpson = simpson, distr = "lnorm")

#output is a list with three elements
even_SAD

rich <- 20
simpson <- 6
uneven_SAD <- fit_SAD(rich = rich, simpson = simpson, distr = "lnorm")



ev<-radplot(even_SAD$rel_abundances) +
  ggplot2::labs(y = "relative abundance", title =NULL)+
  ggplot2::ylim(c(0, 0.4))
un<-radplot(uneven_SAD$rel_abundances) +
  ggplot2::labs(ylab = "relative abundance", title =NULL) +
  ggplot2::ylim(c(0, 0.4))

ev
un


## ----sample from SAD-----------------------------------------------------------------

# diversity of a small sample unlikely to match the simulated diversity values

# first, sample from our simulated SADs

even_sample <- sample_infinite(even_SAD$rel_abundances, 50)
uneven_sample <- sample_infinite(uneven_SAD$rel_abundances, 50)
#sample_infinite returns a numeric vector of sample species abundances
even_sample
uneven_sample

# compare diversity from sample vs. ideal SAD:
# likely pretty far off for a small sample!

# with an even SAD, all diversities lower
even_SAD$community_info
rbind(lapply(c(1, 0, -1), function(l){
  rarity(even_sample, l)
}))

# with an uneven SAD, sample Hill-Simpson can be higher than true Hill-Simpson
# richness is always lower
uneven_SAD$community_info
rbind(lapply(c(1, 0, -1), function(l){
  rarity(uneven_sample, l)
}))


big_even_sample <- sample_infinite(even_SAD$rel_abundances, 1e7)
big_uneven_sample <- sample_infinite(uneven_SAD$rel_abundances, 1e7)

# with a big enough sample, simulated diversities nearly recovered
even_SAD$community_info
rbind(lapply(c(1, 0, -1), function(l){
  rarity(big_even_sample, l)
}))

# with an uneven SAD, sample Hill-Simpson can be higher than true Hill-Simpson
# richness is always lower
uneven_SAD$community_info
rbind(lapply(c(1, 0, -1), function(l){
  rarity(big_uneven_sample, l)
}))



## ----diversity profile---------------------------------------------------------------
# the even and uneven communities have same richness but different Hill diversity when `ell != 1`
ggplot2::ggplot(divpro(even_SAD[[3]]),
                ggplot2::aes(ell, d)) +
  ggplot2::geom_line() +
  ggplot2::ylim(0,22) +
  ggplot2::theme_classic() +
  ggplot2::labs(x = "scaling exponent \'l\'", y = "Hill diversity")

ggplot2::ggplot(divpro(uneven_SAD[[3]]),
                ggplot2::aes(ell, d)) +
  ggplot2::geom_line() +
    ggplot2::ylim(0,22) +
  ggplot2::theme_classic() +
  ggplot2::labs(x = "scaling exponent \'l\'", y = "Hill diversity")





## ----Hill-Simpson is wiggly----------------------------------------------------------
library(furrr)
library(MeanRarity)
plan(strategy = "multiprocess", workers = 7)
evenness<-10^seq(-0.75,-0.35,0.2)
rich <- 100
sample_sizes <- floor(10^seq(1.5, 3, 0.5))
# generate SADs with 100 spp and varying evenness, parametric distributions
SADS<-purrr::flatten(
  purrr::map(
    evenness, function(simp_evenness){
      purrr::map(
        c("lnorm", "gamma"), function(dist){
          fit_SAD(rich = rich
                  , simpson = simp_evenness*(rich-1)+1
                  , distr = dist)
        })
    }))

# set sample size
reps <- 1e3
sample_data<-purrr::map_dfr(SADS, function(mySAD){
  evenness = (mySAD[[2]][3]-1)/(mySAD[[2]][1]-1)
  distribution = mySAD[[1]][1]
    purrr::map_dfr(sample_sizes, function(SS){
      sample_abundances = replicate(reps, sample_infinite(ab = mySAD[[3]], size = SS))
      furrr::future_map_dfr(seq(-1.5, 1.5, 0.01), function(ell){
        true_diversity = rarity(ab = mySAD[[3]], l = ell)
        sample_diversity = sapply(1:reps, function(rep){rarity(ab = sample_abundances[, rep], l = ell)})
        estimated_diversity = sapply(1:reps, function(rep){Chao_Hill_abu(sample_abundances[, rep], l = ell)})
        return(data.frame(evenness
                          , distribution
                          , SS
                          , ell
                          , true_diversity
                          , sample_diversity
                          , estimated_diversity
                          , row.names = NULL))
    })
  })
})


plot_data<-sample_data %>%
  dplyr::group_by(evenness, distribution, ell, SS) %>%
  dplyr::summarize(sample = sd(ifelse(sample_diversity == 0, 0, log(sample_diversity)))
                   , asymptotic = sd(ifelse(estimated_diversity == 0, 0, log(estimated_diversity)))
                   , true_diversity = mean(true_diversity)
                   , mean_sample = mean(sample_diversity)
                   , mean_asymptotic = mean(estimated_diversity)) %>%
  dplyr::mutate(evenness = as.factor(round(evenness, 2))
                , sample_size = SS)




## ----bias figure---------------------------------------------------------------------

# plot for the sample diversity
plot_data %>%
  ggplot2::ggplot(ggplot2::aes(x = ell
                               , y = asymptotic
                               , color = evenness
                               , shape = distribution)) +
  ggplot2::geom_line(ggplot2::aes(color = evenness, linetype = distribution), size = 0.8) +
  ggplot2::theme_classic() +
  ggplot2::xlim(c(-1,1)) +
  ggplot2::scale_color_brewer(palette = "Dark2") +
  ggplot2::facet_wrap(~sample_size, scales = "free_y"
                     , labeller = "label_both") +  #function(x){sapply(x, function(y){paste(y, " individuals")})}) +
  ggplot2::labs(x = "scaling exponent \U2113", y = "scaled variability in asymptotic diversity estimate (sdlog)") +
  ggplot2::scale_y_continuous(limits = c(0, NA),
                              expand = ggplot2::expansion(mult = c(0, 0.1)))



# for the asymptotic estimator
plot_data %>%
  ggplot2::ggplot(ggplot2::aes(x = ell
                               , color = evenness
                               , shape = distribution)) +
  ggplot2::geom_line(ggplot2::aes(y = (mean_asymptotic-true_diversity)/true_diversity, color = evenness, linetype = distribution), size = 0.8) +
  ggplot2::theme_classic() +
  ggplot2::xlim(c(-1,1)) +
  ggplot2::scale_color_brewer(palette = "Set2") +
  ggplot2::facet_wrap(~sample_size
                      , labeller = "label_both") +  #function(x){sapply(x, function(y){paste(y, " individuals")})}) +
  ggplot2::labs(x = "scaling exponent \U2113", y = "scaled average (asymptotic - true diversity)") +
  ggplot2::scale_y_continuous(limits = c(-0.8, 0.8)) +
  ggplot2::geom_hline(yintercept = 0)



## ----table of functions--------------------------------------------------------------
table_dat<-data.frame(
  `Function name` = c("rarity", "rarity_plot", "radplot", "divpro", "sample_infinite", "sample_finite", "fit_SAD")
  , `General purpose` = c("Computation", "Visualization", "Visualization", "Visualization", "Sampling", "Sampling", "Simulation")
  , `Description` = c("Compute Hill diversity using the rarity parameterization")
)

